[env:esp32-pico-devkitm-2]
platform = espressif32
board = esp32-pico-devkitm-2
framework = arduino
board_build.flash_mode = qio
board_build.flash_size = 8MB
monitor_speed = 115200
lib_deps =
    m5stack/M5StickCPlus2@^1.0.0
    bblanchon/ArduinoJson@^7.0.0
    tzapu/WiFiManager@^2.0.0