[platformio]
default_envs = cardputer

[env]
framework = arduino
monitor_speed = 115200

[env:cardputer]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.flash_size = 8MB
board_build.partitions = default_8MB.csv
board_upload.flash_size = 8MB
upload_protocol = esptool
board_build.arduino.memory_type = qio_qspi
build_flags =
    -DCONFIG_IDF_TARGET_ESP32S3
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0
lib_deps =
    m5stack/M5Cardputer@^1.1.1
    https://github.com/bitbank2/AnimatedGIF.git
